# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Test Website
email: krazete@example.com
description: >-
  Exercises for the UCI Chinese 1 course series.
  Originally from an old Berkeley website which only runs on IE.
baseurl: "/test-7038"
url: "https://krazete.github.io"
github_username: krazete

plugins:
  - jekyll-sitemap

# defaults:
#   - scope:
#       type: categories  # select all category pages
#     values:
#       layout: default
#       permalink: categories/:index/

exclude:
  - README.md
